name: Run TODO to Issue
on:
  push:
    branches:
      - master

jobs:
  todo:
    name: TODO to Issue
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        
      - name: TODO to Issue
        uses: alstr/todo-to-issue-action@v5
        with:
          INSERT_ISSUE_URLS: "true"

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v6